### ISSUE TITLE
Action Plan 1

### ISSUE THREAD

**Issue by RohanG326** [RohanG326/dnhsscioly#1]
## TODO:
- [ ] Set roles for group
- [ ] Plan out and make blog for SciOly website
- [ ] Convert to Springboot

## Action Plan:
- [ ] Set roles
- [ ] Brain write (scrumboard)
- [ ] Wireframe
- [ ] Modeling/UML; Behavior, Interaction, Data diagrams

## Team Roles:
- Scrum Master:
  - Rohan G.
- Front End:
  - Nathan
  - Nicky
- Back End:
  - Don
  - Bailey
  - Meng
  - Krish
  - Nick
- Dev Ops:
  - Everyone (upholds development process)

**Comment by dontran15** [comment]
## Science Olympiad Website
The central goal of our website is to provide a website that will enable our club to easily manage members, provide a comprehensive archive or resources, implementations of important processes (registering, event placement, team selection, competing), and provide easy communication of announcements.

## Brain Write
### General Program Designs
- Actual Tangible Website Design
- Abstracted User Data (Name, Contact Info, Events, Teams, Grades, Username, Password, Email, Phone Number, Discord, Experience, Role)
- User Management (Assigning/Changing Editing User Data, Log Ins, Events/Team Organization, Levels of Access, etc.)
- Formatting of Data Into a Table (Quick Access to All Data)

### Wire Frame
<img width="722" alt="image" src="https://user-images.githubusercontent.com/75715248/192323674-c164b91d-3d8b-4dd4-919d-c1cd558ca982.png">

Global Nav/Pages
- Home Page
- Account/Event Dashboard/Registration
- About
- Calendar
- Resources (Wiki/Archives/Photos/Other Club Resources)
- Administration Tools
- Individual Event Pages (Access for Members, Can be Edited by Students)

### Other Ideas
- Canvas Design of Website
  - Home Page
  - Account Management
  - Dashboard/Event List
  - Calendar (Integrating Google Calendar?)
  - Individual Event pages
  - Assignments (Tests, Assignments)
- Data 
  - Accounts (Name (first & last), Usernames, Roles, Contact Info, Events, Teams)
  - Contact Info (Phone #, Email, Discord)
  - Log In System
  - Easily Navigable Catalog/Archive of Presentation, Tests, Materials
- Event/Team Management
- Competition Phases
- Search Bar
- Blogging
- Integration of Discord, scioly.org, scilympiad (competition part), Zoom, Email
- Elections
- Administration Features
- Image Processing and Archiving
- Finance Management
- More...
